version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo_izifile
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: izifile_backend
    depends_on:
      - mongo
    ports:
      - "3500:3500"
    environment:
      - MONGODB_CNN=mongodb://mongo:27017/izifile
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo_data:
